djangoSistemaBase/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('home/', include('home.urls')),
]

home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

urlpatterns = [
    
    # acceso por defecto
    path('', views.home, name='home'),
    path('create', views.create,name='create'),
    path('update', views.update, name='update'),

    #Employees CRUD
    path('edit/<int:id>/employee', views.edit_employee, name='edit_employee'),
    path('delete/<int:id>/employee', views.delete_employee, name='delete_employee'),
    path('view/<int:id>/employee', views.view_employee, name='view_employee'),
    path('create/emp', views.create_employee,name='create_employee'),
    path('create/employee_add', views.employee_add,name='employee_add'),

    #Tools CRUD
    path('edit/<int:id>/tools', views.edit_tools, name='edit_tools'),
    path('delete/<int:id>/tools', views.delete_tools, name='delete_tools'),
    path('view/<int:id>/tools', views.view_tools, name='view_tools'),
    path('create/tool', views.create_tools,name='create_tools'),
    path('create/tool_add', views.tool_add,name='tool_add'),

    #Moves CRUD
    path('edit/<int:id>/move', views.edit_moves, name='edit_move'),
    path('delete/<int:id>/move', views.delete_moves, name='delete_move'),
    path('view/<int:id>/move', views.view_moves, name='view_move'),
    path('create/<str:type>/move', views.create_moves,name='create_move'),
    path('create/move_add', views.move_add,name='move_add'),

    #Moves CRUD
    path('edit/<int:id>/certification', views.edit_certification, name='edit_certification'),
    path('delete/<int:id>/certification', views.delete_certification, name='delete_certification'),
    path('view/<int:id>/certification', views.view_certification, name='view_certification'),
    path('create/certification', views.create_certification,name='create_certification'),
    path('create/certification_add', views.certification_add,name='certification_add'),
    
    #path('getServicio', views.getMove, name='getmove'),
    path('read', views.read,name='read'),
    path('delete', views.delete,name='delete'),
    path('employees',views.employees,name='employees'),
    path('tools',views.tools,name='tools'),
    path('moves',views.moves,name='moves'),
    path('movetype',views.movetype,name='movetype'),
    path('inform',views.inform,name='inform'),
    path('certification',views.certification,name='certification'),
    
]

toolAdmin/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('home/', include('home.urls')),
]

home/models.py
from django.db import models
from login.models import *


class EmployeeManager(models.Manager):

    def basic_validator(self, postData):
        pass


class Employee(models.Model):

    #id = models.AutoField(db_column='id',primary_key=True)
    name = models.CharField(max_length=45, blank=True, null=False, default='DeFault_Name')
    last_name = models.CharField(max_length=45, blank=True, null=True)
    position = models.CharField(max_length=45, blank=True, null=True)
    area = models.CharField(max_length=45, blank=True, null=True)
    active = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = EmployeeManager()

    def __str__(self):
        return str(self.id) + '. - ' + self.name + ' ' + self.last_name


class Warehouse(models.Model):
    name = models.CharField(max_length=45, blank=True, null=False,default='Bodega_DeFault')


class ToolManager(models.Manager):
    # TODO do validation basic_validator
    def basic_validator(self, postData):
        pass

# El atributo assigned_at es nulo si la herramienta está disponible en Bodega de Almacenamiento

class Tool(models.Model):
    # Incluir las fechas de certificación, vencimiento y períodos y accesos a documentos
    #id = models.AutoField(db_column='id',primary_key=True)
    name = models.CharField(max_length=45, blank=True, null=False, default='Tool_DeFault')
    serie = models.CharField(max_length=30, blank=True, null=True)
    model = models.CharField(max_length=45, blank=True, null=True)
    provider = models.CharField(max_length=45, blank=True, null=True)
    cost = models.IntegerField(blank=True, null=True)
    assigned_at = models.ForeignKey(Employee,
                                    related_name='assigned_at',
                                    on_delete=models.DO_NOTHING,
                                    null=True)
    belong_to = models.ForeignKey(Warehouse,
                                related_name='belong_to',
                                on_delete=models.DO_NOTHING,
                                null=True)
    created_for = models.ForeignKey(
        User, related_name='tool_created_for', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=False)
    objects = ToolManager()

    def __str__(self):
        return 'N°: ' + self.serie + '-' + self.name


class CertificationManager(models.Manager):

    def basic_validator(self, postData):
        pass


class Certification(models.Model):
    tool = models.OneToOneField(Tool,
                                related_name='certification',
                                on_delete=models.DO_NOTHING,
                                null=True)
    is_necessary = models.BooleanField(default=False)
    last_certification = models.DateTimeField()
    certification_period = models.IntegerField(
        default=180)  # 180 dìas (6 meses) de certificación por defecto
    created_for = models.ForeignKey(
        User, related_name='certification_created_for', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = CertificationManager()


class MovesType(models.Model):
    #id = models.AutoField(db_column='id',primary_key=True)
    type = models.CharField(max_length=45, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.type


class Role(models.Model):
    #id = models.AutoField(db_column='id',primary_key=True)
    description = models.CharField(max_length=45, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user_email = models.CharField(max_length=255)


class MoveManager(models.Manager):

    def basic_validator(self, postData):
        pass

# Se define que cualquier emplado puede realizar un movimiento de ENTRADA de una herramienta
# a una bodega asignada por quien recibe la misma. 
# Además se define que la persona que saque la herramienta automáticamente se convierte en el responsable del movimiento y la herramienta.
# La clase herramienta tien dos atributos assigned_at y belong_to, que se actualizan en el momento de la creación del movimiento.

class Move(models.Model):
    #id = models.AutoField(db_column='id',primary_key=True)
    move_type = models.ForeignKey(MovesType,
                                related_name='moves_type_has_tools',
                                on_delete=models.CASCADE)
    tool = models.ForeignKey(Tool,
                            related_name='tool_moved',
                            on_delete=models.CASCADE)
    employee = models.ForeignKey(Employee,
                                related_name='moves_employee_tools',
                                on_delete=models.CASCADE)
    description = models.CharField(max_length=255, blank=True, null=True)
    approved_for = models.ForeignKey(
        User, related_name='user_approved', on_delete=models.CASCADE)
    #Cambio asociado a tipo de documento y su número en cada movimiento generado
    document_type = models.CharField(max_length=255, blank=True, null=True)
    document_number = models.CharField(max_length=255, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.move_type.type + ' - ' + self.tool.name + ' - ' + self.employee.name

home/templates/home/certification.html
{% extends 'maincontent.html' %} 
{% block content %}

{% endblock %}

home/templates/home/create_emp.html
{% extends 'maincontent.html' %} {% block content %}

<div class="content">
    <div class="container-fluid">
        <section id="content" class="content">
            <div class="row">
                <div id="content-main" class="col-12">
                    <form action="{% url 'home:employee_add' %}" method="post" id="employee_form" novalidate>
                        {% csrf_token %}
                        <div class="row">
                            <!-- Para Ingresar los datos -->
                            <div class="col-lg-8">
                                <div class="card card-primary card-outline">
                                    <div class="card-header">
                                        <h3 class="card-title">Complete la Información del Trabajador</h3>
                                    </div>
                                    <div class="card-body">
                                        <div class="form-group field-name">
                                            <div class="row">
                                                <label class="col-sm-2 text-left" for="id_name">Nombre</label>
                                                <div class=" col-sm-10 field-name">
                                                    <input type="text" name="name" class="vTextField" maxlength="45" id="id_name">
                                                    <div class="help-block red">
                                                    </div>
                                                    <div class="help-block text-red">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group field-last_name">
                                            <div class="row">
                                                <label class="col-sm-2 text-left" for="id_last_name">Apellido</label>
                                                <div class=" col-sm-10 field-last_name">
                                                    <input type="text" name="last_name" class="vTextField" maxlength="45" id="id_last_name">
                                                    <div class="help-block red">
                                                    </div>
                                                    <div class="help-block text-red">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group field-position">
                                            <div class="row">
                                                <label class="col-sm-2 text-left" for="id_position">Cargo</label>
                                                <div class=" col-sm-10 field-position">
                                                    <input type="text" name="position" class="vTextField" maxlength="45" id="id_position">
                                                    <div class="help-block red">
                                                    </div>
                                                    <div class="help-block text-red">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group field-area">
                                            <div class="row">
                                                <label class="col-sm-2 text-left" for="id_area">Area Laboral</label>
                                                <div class=" col-sm-10 field-area">
                                                    <input type="text" name="area" class="vTextField" maxlength="45" id="id_area">
                                                    <div class="help-block red">
                                                    </div>
                                                    <div class="help-block text-red">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group field-active">
                                            <div class="row">
                                                <label class="col-sm-2 text-left" for="id_active">Activo</label>
                                                <div class=" col-sm-10 field-active">
                                                    <input type="checkbox" name="active" id="id_active" checked>
                                                    <div class="help-block red">
                                                    </div>
                                                    <div class="help-block text-red">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                            <!-- Para las Acciones -->
                            <div class="card card-primary card-outline">
                                <div class="card-header">
                                    <h3 class="card-title"><i class="fas fa-edit"></i> Acciones</h3>
                                </div>
                                <div class="card-body">
                                    <div class="form-group">
                                        <input type="submit" value="Guardar" class="btn btn-outline-success form-control" name="_save">
                                    </div>
                                    <div class="form-group">
                                        <input type="submit" class="btn btn-outline-info form-control" value="Guardar y añadir otro" name="_addanother">
                                    </div>
                                    <div class="form-group">
                                        <input type="submit" class="btn btn-outline-info form-control" value="Guardar y continuar editando" name="_continue">
                                    </div>
                                </div>
                                <!-- Fin de Acciones -->
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </section>
    </div>
</div>
{% endblock %}

home/templates/home/create_tool.html
{% extends 'maincontent.html' %} {% block content %}
<div class="content">
    <div class="container-fluid">
        <section id="content" class="content">
            <div class="row">
                <div id="content-main" class="col-12">
                    <form action="{% url 'home:tool_add' %}" method="post" id="tool_form" novalidate="">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-12 col-lg-9">
                                <div class="card card-primary card-outline">
                                    <div class="card-header">
                                        <div class="card-title">
                                            Añadir Herramienta
                                        </div>
                                    </div>
                                    <div class="card-body">
                                        <div class="form-group field-name">
                                            <div class="row">
                                                <label class="col-sm-2 text-left" for="id_name">Nombre</label>
                                                <div class=" col-sm-10 field-name">
                                                    <input type="text" name="name" class="vTextField" maxlength="45" id="id_name">
                                                    <div class="help-block red">
                                                    </div>
                                                    <div class="help-block text-red">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group field-serie">
                                            <div class="row">
                                                <label class="col-sm-2 text-left" for="id_serie">Serie</label>
                                                <div class=" col-sm-10 field-serie">
                                                    <input type="text" name="serie" class="vTextField" maxlength="30" id="id_serie">
                                                    <div class="help-block red">
                                                    </div>
                                                    <div class="help-block text-red">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group field-model">
                                            <div class="row">
                                                <label class="col-sm-2 text-left" for="id_model">Model</label>
                                                <div class=" col-sm-10 field-model">
                                                    <input type="text" name="model" class="vTextField" maxlength="45" id="id_model">
                                                    <div class="help-block red">
                                                    </div>
                                                    <div class="help-block text-red">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group field-provider">
                                            <div class="row">
                                                <label class="col-sm-2 text-left" for="id_provider">Proveedor</label>
                                                <div class=" col-sm-10 field-provider">
                                                    <input type="text" name="provider" class="vTextField" maxlength="45" id="id_provider">
                                                    <div class="help-block red">
                                                    </div>
                                                    <div class="help-block text-red">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group field-cost">
                                            <div class="row">
                                                <label class="col-sm-2 text-left" for="id_cost">Costo</label>
                                                <div class=" col-sm-10 field-cost">
                                                    <input type="number" name="cost" class="vIntegerField" id="id_cost">
                                                    <div class="help-block red">
                                                    </div>
                                                    <div class="help-block text-red">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group field-assigned_at">
                                            <div class="row">
                                                <label class="col-sm-2 text-left" for="id_assigned_at">Asignada a:<span class="text-red">* </span></label>
                                                <div class=" col-sm-10 field-assigned_at">
                                                    <div class="related-widget-wrapper">
                                                        <select name="assigned_at" required="" id="id_assigned_at" data-select2-id="select2-data-id_assigned_at" tabindex="-1" class="select2-hidden-accessible" aria-hidden="true">
                                                        <option value="" selected="" data-select2-id="select2-data-2-e9px">---------</option>
                                                        {% for employee in employees%}
                                                            <option value="{{employee.id}}">{{ employee.name }}</option>
                                                        {% endfor %}
                                                        </select>
                                                        {% comment %}                                           
                                                        <a class="related-widget-wrapper-link change-related" id="change_id_assigned_at" data-href-template="/admin/home/employee/__fk__/change/?_to_field=id&amp;_popup=1" title="Cambiar employee seleccionados"><img src="/static/admin/img/icon-changelink.svg" alt="Modificar"></a>
                                                        <a class="related-widget-wrapper-link add-related" id="add_id_assigned_at" href="/admin/home/employee/add/?_to_field=id&amp;_popup=1" title="Añadir otro employee"><img src="/static/admin/img/icon-addlink.svg" alt="Añadir"></a>
                                                        <a class="related-widget-wrapper-link delete-related" id="delete_id_assigned_at" data-href-template="/admin/home/employee/__fk__/delete/?_to_field=id&amp;_popup=1" title="Eliminar employee seleccionada/o"><img src="/static/admin/img/icon-deletelink.svg" alt="Eliminar"></a> 
                                                        {% endcomment %}
                                                    </div>
                                                    <div class="help-block red">
                                                    </div>
                                                    <div class="help-block text-red">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group field-belong_to">
                                            <div class="row">
                                                <label class="col-sm-2 text-left" for="id_belong_to">Bodega Asignada<span class="text-red">* </span></label>
                                                <div class=" col-sm-10 field-belong_to">
                                                    <div class="related-widget-wrapper">
                                                        <select name="belong_to" required="" id="id_belong_to" data-select2-id="select2-data-id_belong_to" tabindex="-1" class="select2-hidden-accessible" aria-hidden="true">
                                                        <option value="" selected="" data-select2-id="select2-data-4-g2yd">---------</option>
                                                        <!-- Hacer loops con Bodegas -->
                                                        {% for warehouse in warehouses %}
                                                            <option value="{{warehouse.id}}">{{ warehouse.name }}</option>
                                                        {% endfor %}
                                                        <!-- End Loops Bodegas -->
                                                        </select>
                                                        {% comment %} 
                                                        <a class="related-widget-wrapper-link change-related" id="change_id_belong_to" data-href-template="/admin/home/warehouse/__fk__/change/?_to_field=id&amp;_popup=1" title="Cambiar warehouse seleccionados"><img src="/static/admin/img/icon-changelink.svg" alt="Modificar"></a>
                                                        <a class="related-widget-wrapper-link add-related" id="add_id_belong_to" href="/admin/home/warehouse/add/?_to_field=id&amp;_popup=1" title="Añadir otro warehouse"><img src="/static/admin/img/icon-addlink.svg" alt="Añadir"></a>
                                                        <a class="related-widget-wrapper-link delete-related" id="delete_id_belong_to" data-href-template="/admin/home/warehouse/__fk__/delete/?_to_field=id&amp;_popup=1" title="Eliminar warehouse seleccionada/o"><img src="/static/admin/img/icon-deletelink.svg" alt="Eliminar"></a>
                                                        {% endcomment %}
                                                    </div>
                                                    <div class="help-block red">
                                                    </div>
                                                    <div class="help-block text-red">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group field-active">
                                            <div class="row">
                                                <label class="col-sm-2 text-left" for="id_active">Active</label>
                                                <div class=" col-sm-10 field-active">
                                                    <input type="checkbox" name="active" id="id_active" checked="">
                                                    <div class="help-block red">
                                                    </div>
                                                    <div class="help-block text-red">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- End Form Tool -->
                            <div class="col-12 col-lg-3">
                                <div id="jazzy-actions" class="">
                                    <div class="card card-primary card-outline">
                                        <div class="card-header">
                                            <h3 class="card-title">
                                                <i class="fas fa-edit"></i> Acciones
                                            </h3>
                                        </div>
                                        <div class="card-body">
                                            <div class="form-group">
                                                <input type="submit" value="Guardar" class="btn btn-outline-success form-control" name="_save">
                                            </div>
                                            <div class="form-group">
                                                <input type="submit" class="btn btn-outline-info form-control" value="Guardar y añadir otro" name="_addanother">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </section>
    </div>
</div>
{% endblock %}

home/templates/home/edit_move.html
{% extends 'maincontent.html' %} 
{% block content %}

{% endblock %}

home/templates/home/employees.html
{% extends 'maincontent.html' %} {% block content %}
<div>
    <div class="col-md">
        <h1>Listado de Trabajadores</h1>
    </div>
    <hr>
    <div class="col-md-3">
        <a href="{% url 'home:create_employee' %}" class="btn btn-primary">Ingresar Nuevo Trabajador</a>
    </div>
    <hr>
</div>
<br>
<div>
    <table class="table table-striped " id="data">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nombre</th>
                <th scope="col">Apellido</th>
                <th scope="col">Cargo</th>
                <th scope="col">Area</th>
                <th scope="col">Ingreso</th>
                <th scope="col">Accion</th>
            </tr>
        </thead>
        <tbody>
            {% for employee in employees%}
            <tr>
                <td scope="row">{{ employee.id }}</td>
                <td>{{employee.name}}</td>
                <td>{{employee.last_name}}</td>
                <td>{{employee.position}}</td>
                <td>{{employee.area}}</td>
                <td>{{employee.created_at|date:"Y-m-d"}}</td>
                <td>
                    <a href="{% url 'home:delete_employee' employee.id %}" class="btn btn-danger">Delete</a>
                    <a href="{% url 'home:edit_employee' employee.id %}" class="btn btn-warning">Edit</a>
                    <a href="{% url 'home:view_employee' employee.id %}" class="btn btn-success">View</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}