djangoSistemaBase/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('home/', include('home.urls')),
]

home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

urlpatterns = [
    
    # acceso por defecto
    path('', views.home, name='home'),
    path('create', views.create,name='create'),
    path('update', views.update, name='update'),

    #Employees CRUD
    path('edit/<int:id>/employee', views.edit_employee, name='edit_employee'),
    path('delete/<int:id>/employee', views.delete_employee, name='delete_employee'),
    path('view/<int:id>/employee', views.view_employee, name='view_employee'),
    path('create/emp', views.create_employee,name='create_employee'),
    path('create/employee_add', views.employee_add,name='employee_add'),

    #Tools CRUD
    path('edit/<int:id>/tools', views.edit_tools, name='edit_tools'),
    path('delete/<int:id>/tools', views.delete_tools, name='delete_tools'),
    path('view/<int:id>/tools', views.view_tools, name='view_tools'),
    path('create/tool', views.create_tools,name='create_tools'),
    path('create/tool_add', views.tool_add,name='tool_add'),

    #Moves CRUD
    path('edit/<int:id>/move', views.edit_moves, name='edit_move'),
    path('delete/<int:id>/move', views.delete_moves, name='delete_move'),
    path('view/<int:id>/move', views.view_moves, name='view_move'),
    path('create/<str:type>/move', views.create_moves,name='create_move'),
    path('create/move_add', views.move_add,name='move_add'),

    #Moves CRUD
    path('edit/<int:id>/certification', views.edit_certification, name='edit_certification'),
    path('delete/<int:id>/certification', views.delete_certification, name='delete_certification'),
    path('view/<int:id>/certification', views.view_certification, name='view_certification'),
    path('create/certification', views.create_certification,name='create_certification'),
    path('create/certification_add', views.certification_add,name='certification_add'),
    
    #path('getServicio', views.getMove, name='getmove'),
    path('read', views.read,name='read'),
    path('delete', views.delete,name='delete'),
    path('employees',views.employees,name='employees'),
    path('tools',views.tools,name='tools'),
    path('moves',views.moves,name='moves'),
    path('movetype',views.movetype,name='movetype'),
    path('inform',views.inform,name='inform'),
    path('certification',views.certification,name='certification'),
    
]

toolAdmin/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('home/', include('home.urls')),
]

templates/asidebarizq.html
 {% load static %}
 <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
    <div class="p-3">
      <h5>Title</h5>
      <p>Sidebar content</p>
    </div>
  </aside>
  <!-- /.control-sidebar -->

templates/base.html
{% load static %}
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title>AdminTool 1.0</title>
  <!-- Incluyo Font Awesome Script-->
  <script src="https://kit.fontawesome.com/1578592595.js" crossorigin="anonymous"></script>
  
  <!-- Font Awesome Icons -->
  <!--<link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">-->
  
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
<link rel="stylesheet" href="https://cdn.datatables.net/1.11.0/css/jquery.dataTables.min.css"/>
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.0.0/css/buttons.dataTables.min.css"/>


<link rel="stylesheet" href="{% static 'plugins/datatables-1.10.20/css/dataTables.bootstrap4.min.css' %}"/>
<link rel="stylesheet" href="{% static 'plugins/datatables-1.10.20/plugins/responsive-2.2.3/css/responsive.bootstrap4.min.css' %}"/>

<script src="{% static 'plugins/datatables-1.10.20/js/jquery.dataTables.js' %}"></script>
<script src="{% static 'plugins/datatables-1.10.20/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-1.10.20/plugins/responsive-2.2.3/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables-1.10.20/plugins/responsive-2.2.3/js/responsive.bootstrap4.min.js' %}"></script>
<script src="https://cdn.datatables.net/1.11.0/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.0.0/js/dataTables.buttons.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/2.0.0/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.0.0/js/buttons.print.min.js"></script>


<!--https://code.jquery.com/jquery-3.5.1.js-->

</head>
{% block body %}
<!--Bloque donde se cargaran las paginas html-->
{% endblock %}


</html>

templates/body.html
{% extends 'base.html' %} {% load static %} {% block body %}

<body class="hold-transition sidebar-mini">
    <div class="wrapper">

        {% include 'navbar.html' %} {% include 'sidebar.html' %} {% block wrapper %} {% endblock %} {% include 'asidebarizq.html' %} {% include 'footer.html'%}
    </div>
    <!-- ./wrapper -->
    {% block scripts %}
    
    <!-- jQuery -->
    <!-- Para Modificar los datatables con el id indicado -->
    <script type="application/javascript">
        $(function() {
            $('#data').DataTable({
                responsive: true,
                autoWidth: false,
                dom: 'lfrtBip',
                buttons: [
                    'copy', 'csv', 'excel', 'pdf', 'print'
                ],
                "language": {
                    "lengthMenu": "Mostar _MENU_ registros por página",
                    "zeroRecords": "No se encontraron registros - lo sentimos",
                    "info": "Mostrando página _PAGE_ de _PAGES_",
                    "infoEmpty": "No existen registros disponibles",
                    "infoFiltered": "(encontrados de _MAX_ registros totales)",
                    "search": "Buscar: ",
                    "paginate": {
                        "first": "Primero",
                        "last": "Último",
                        "next": "Siguiente",
                        "previous": "Anterior"
                    },
                },
            });
        });
        $(function() {
            $('#data_1').DataTable({
                responsive: true,
                autoWidth: false,
                dom: 'lfrtBip',
                buttons: [
                    'copy', 'csv', 'excel', 'pdf', 'print'
                ],
                language: {
                    "lengthMenu": "Mostar _MENU_ registros por página",
                    "zeroRecords": "No se encontraron registros. Intenta otra búsqueda",
                    "info": "Mostrando página _PAGE_ de _PAGES_",
                    "infoEmpty": "No existen registros disponibles",
                    "infoFiltered": "(encontrados de _MAX_ registros totales)"
                },
            });
        });
    </script>

    {% endblock %}
</body>
{% endblock %}

templates/footer.html
{% load static %}
<!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
      AdminTools
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2020-2021 <a href="https://ainel.cl">AINEL LTDA</a>.</strong> All rights reserved.
  </footer>

templates/maincontent.html
{% extends 'wrapper.html' %}
{% load static %}

{% block maincontent %}
    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            {% block content %}

            {% endblock %}
          </div>
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  {% endblock %}

templates/navbar.html
{% load static %}
<!-- Navbar -->

<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <div class="row">
        <!-- Left navbar links -->
        <div class="col-md inline-block">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="{% url 'home:home' %}" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="{% url 'home:home' %}" class="nav-link">Inicio</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="{% url 'home:employees' %}" class="nav-link">Trabajadores</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="{% url 'home:tools' %}" class="nav-link">Herramientas</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="{% url 'home:moves' %}" class="nav-link">Movimientos</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="{% url 'home:certification' %}" class="nav-link">Certificaciones</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="{% url 'home:inform' %}" class="nav-link">Informes</a>
                </li>
            </ul>
        </div>
    </div>
    <!--
    <div class="col-md-4 inline-block">
        <form class="form">
            <div class="input-group input-group-sm">
                <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                <div class="input-group-append">
                    <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                </button>
                </div>
            </div>
        </form>
    </div>
    -->
    <div class="col-md offset-sm-1 inline-block float-right">
        <!-- Right navbar links -->
        <!--<ul class="navbar-nav">
            <li class="breadcrumb-item"><a href="{% url 'home:home' %}">Home</a></li>
            <li class="breadcrumb-item active"><a href="/logout">Logout</a></li>
        </ul> -->
    </div>
</nav>
<!-- /.navbar -->

templates/scriptsbody.html
{% load static %}

{% block  scripts %}
<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
{% endblock  %}

templates/sidebar.html
{% load static %}

<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
        <img src="{% static 'dist/img/logo_ainel.png' %}" alt="AdminLTE Logo" class="brand-image img-rect" style="opacity: .8">
        <span class="brand-text font-weight-light">AdminTools</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar User panel -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{% static 'dist/img/user2-160x160.jpg' %}" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">{{active_user.name}} {{active_user.last_name}}</a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class with font-awesome or any other icon font library -->
                <li class="nav-item has-treeview menu-open">
                    <a href="#" class="nav-link active">
                        <i class="nav-icon fas fa-list"></i>
                        <p>
                            Menú Gestión
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{% url 'home:home' %}" class="nav-link">
                                <i class="fas fa-home nav-icon"></i>
                                <p>Inicio</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'home:employees' %}" class="nav-link">
                                <i class="fas fa-user nav-icon"></i>
                                <p>Trabajadores</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'home:tools' %}" class="nav-link">
                                <i class="nav-icon fas fa-toolbox"></i>
                                <p>Herramientas</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'home:moves' %}" class="nav-link">
                                <i class="nav-icon fas fa-dolly"></i>
                                <p>Movimientos</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'home:certification' %}" class="nav-link">
                                <i class="nav-icon fas fa-check-double"></i>
                                <p>Certificaciones</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'home:inform' %}" class="nav-link">
                                <i class="nav-icon fas fa-chart-bar"></i>
                                <p>Informes</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/logout" class="nav-link">
                                <i class="nav-icon fas fa-door-open"></i>
                                <p>Logout</p>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

templates/wrapper.html
{% extends 'body.html' %}
{% load static %}
{% block wrapper %}
<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
{% block maincontent %}

{% endblock  %}
  </div>
  <!-- /.content-wrapper -->
{% endblock  %}